### ISSUE TITLE
Incorrect keys in Location updates dictionary

### ISSUE THREAD

**Issue by byroncoetsee** [benzamin/BBLocationManager#1]
Hey there,

Thanks for the awesome library :)

I have one issue and one suggestion... If I may...

```
/**
     *   Gives an Location Dictionary using keys BB_LATITUDE, BB_LONGITUDE, BB_ALTITUDE
     */
    public func bbLocationManagerDidUpdateLocation(_ latLongAltitudeDictionary: [AnyHashable : Any]!) {  }
```

Those keys are incorrect. The keys used in the dictionary seem to be `latitude`, `longitude` and `altitude`.

Suggestion:

Maybe make some of the the delegate methods optional so we don't have to include all of them in the delegate class :)

Cheers!

**Comment by benzamin** [comment]
Hey Byron,
Thanks for you issue and suggestion. Here are the answers:

**Issue:** Actually BB_LATITUDE, BB_LONGITUDE, BB_ALTITUDE aren't keys, the are defined macros whose actual string values are "latitude", "longitude" and "altitude". As the documentation says the are keys, that's why the confusion. I'm updating my documentation, thanks for pointing out!
**Suggestion:** I totally agree with you. Will make only one delegate method as required.

Thanks again 👍

**Comment by byroncoetsee** [comment]
Ah ok I see! 

Awesome. And thank you, again 👍
